[package]
name = "wh_music"
version = "0.1.0"
authors = ["Maix0 <maix522@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.2.1"
wh_core={path="../wh_core"}


log="0.4.14"
serenity="0.10.5"
songbird="0.1.6"