[package]
name = "wh_core"
version = "0.1.0"
authors = ["Maix0 <maix522@gmail.com>"]
edition = "2018"



[dependencies]
log = "0.4.14"
serenity= "0.10.5"

[dependencies.fern]
features = ["colored"]
version = "0.6.0"

